version: 2.1
orbs:
  node: circleci/node@3.0.0
  python: circleci/python@0.2.1
  twilio: circleci/twilio@1.0.0
  
jobs:
  #build:
  #  executor: python/default
  #  steps:
  #    - checkout
  #    - python/load-cache
  #    - python/install-deps
  #    - python/save-cache
  #    - run: python3 ipl21.py 
  fanzy_job_with_sms:
    executor: python/default    
    #docker:
    #  - image: 'cimg/base:edge'
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python3 ipl21.py 
      - twilio/install
      #- twilio/sendsms:
      #    body: Hi ra Chakri, from Alwala, message 3
      #    from: '+15752152911'
      #    to: '+919550593328'
      - twilio/sendsms:
          body: Hi from Alwala, message 4
          from: '+15752152911'
          to: '+919133416306'

workflows:
  nightly:
    # triggers:
    #   - schedule:
    #       cron: "30 20 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - master

    jobs:
      #- build
      - fanzy_job_with_sms