version: 2.1
orbs:
  python: circleci/python@0.2.1
  twilio: circleci/twilio@1.0.0
  node: circleci/node@3.0.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python3 ipl21.py 
  alert:
      executor:
        name: node/default
      steps:
        - twilio/sendsms:
            body: Customized alert message for this job

workflows:
  nightly:
    # triggers:
    #   - schedule:
    #       cron: "30 20 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - master

    jobs:
      #- build
      - alert