version: 2.1
orbs:
  node: circleci/node@3.0.0
  python: circleci/python@0.2.1
  twilio: circleci/twilio@1.0.0
  
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python3 ipl21.py 
  sms_job:
    docker:
      - image: 'cimg/base:edge'
    steps:
      - twilio/install
      - twilio/sendsms:
          body: Hi from whatsapp
          from: 'whatsapp:+15752152911'
          to: 'whatsapp:+919133416306'

workflows:
  nightly:
    # triggers:
    #   - schedule:
    #       cron: "30 20 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - master

    jobs:
      #- build
      - sms_job