version: 2.1
orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python ipl21.py 

workflows:
   nightly:
     triggers:
       - schedule:
           cron: "44 3 * * *"
           filters:
             branches:
               only:
                 - circle-ci
     jobs:
       - build
