version: 2.1
orbs:
  python: circleci/python@0.2.1
  twilio: circleci/twilio@1.0.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python3 ipl21.py 
  alert:
      docker:
        - image: 'cimg/node:14.4.0'
      environment: 
        - TWILIO_AUTH_TOKEN: '3f3d1d86af4885996bc4f7144df24e02'
      steps:
        - twilio/install
        - twilio/alert:
            body: Customize alert message for this job
            from: 'whatsapp:+14155238886'
            to: 'whatsapp:+919133416306'
            authtoken: TWILIO_AUTH_TOKEN
            sid: 'ACd03277db40dc83c312e147c637864b2a'
  #twililo: circleci/twilio@volatile


workflows:
  nightly:
    # triggers:
    #   - schedule:
    #       cron: "30 20 * * *"
    #       filters:
    #         branches:
    #           only:
    #             - master

    jobs:
      #- build
      - alert