version: 2.1
orbs:
  node: circleci/node@3.0.0
  python: circleci/python@0.2.1
  twilio: circleci/twilio@1.0.0
  
jobs:
  fanzy_job_with_sms:
    executor: python/default    
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: python3 ipl21.py 
      - twilio/install
      - twilio/sendsms:
          body: Hi Alwala, fanzy sheet updated check 1
          from: '+15752152911'
          to: '+919133416306'

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "27 14 * * *"
          filters:
            branches:
              only:
                - test
    jobs:
      - fanzy_job_with_sms
  sat_and_sun:
    triggers:
      - schedule:
          cron: "25 14 * * 2,0"
          filters:
            branches:
              only:
                - test
    jobs:
      - fanzy_job_with_sms
